add all files
Danik2021/goit-markup-hw-01 pull request #1
Opened 2024-02-05 11:35 UTC by Danik2021

2024-02-06 07:02 UTC, xrustic2020 requested changes
Треба переглянути імена для класів та оптимізувати їх в плані коли в тебе однакові елементи для них не потрібно для кожного створювати окремо клас, їм треба просто дати той самий клас. А так в цілому дуже непогано для першого разу)
Бачу ти навіть css написав, але перша домашка там без css можна було)

2024-02-06 07:02 UTC, xrustics commented on index.html
> +          <a class="email" href="info@devstudio.com">info@devstudio.com</a>
Тут було б непогано додати до пошти mailto:

2024-02-06 07:02 UTC, xrustics commented on index.html
> +        <section class="section-one">
Краще не використовувати назви класів типу  "section-one", краще їх називати щоб ти розумів що там. Наприклад "baner", тощо. Просто по іншому ти потім в майбутньому не розберешся що де у тебе на сторінці) уяви ситуацію, коли в тебе таких може бути 100 секцій і тобі треба редагувати стилі з банеру) і ти такий підеш спочатку гортати html шукати який там класс section-4 чи section-10) а маючи більш чітку назву ти просто сразу йдеш в css файл та розумієш що тобі треба редагувати селектор для класу "baner"

2024-02-06 07:02 UTC, xrustics commented on index.html
> +            <dl>
Це не зовсім той випадок для використання тегів dl, dt, dd, вони більш підходять коли в тебе прям якийсь словник, типу вікіпедії, тобто коли в тебе є якесь поняття та роз'яснення до цього поняття. Типу як словник слів, по аналогії вікіпедії. Взагалі ці теги рідко використовуються в дуже специфічних ситуаціях, хіба коли будеш писати сайт словник)

2024-02-06 07:02 UTC, xrustics commented on index.html
> +            <dl>
Тут краще використовувати список, у якому кожен блок це буде li який буде містити якийсь h3 і p

2024-02-06 07:02 UTC, xrustics commented on index.html
> +            <div class="cont-img-work">
Це теж список а не просто в div) 
Коли ти бачиш декілька однотипних елементів - це скоріше за все список)

2024-02-06 07:02 UTC, xrustics commented on index.html
> +          <div class="cont-section-four">
І це теж список карточок людей команди, його треба в ul > li. По суті це однотипні елементи. Типу однакові карточки і все відноситься до одного - це список людей команди

2024-02-06 07:02 UTC, xrustics commented on index.html
> +          <div class="cont-section-four">
Після заголовку всі картки то ul > li

2024-02-06 07:02 UTC, xrustics commented on index.html
> +              <figure class="figure-two">
Ну з назвою класів треба щось придумати) бо картинка-1, картинка-2 це буде дуже важко підтримувати. Треба більш чіткі назви, щоб ти розумів що це за картинка по назві.

2024-02-06 07:02 UTC, xrustics commented on index.html
> +                <p class="specialty-two">Frontend Developer</p>
Мені здається тут тобі не потрібно мати декілька класів specialty-one, specialty-two і т.д. Там же стилі однакові для кожної такої фрази, тому можна просто створити один клас типу specialty і його навішати на кожен елемент такої фрази. Таким чином ти перевикористаєш код

2024-02-06 07:02 UTC, xrustics commented on index.html
> +            <a class="email-two" href="info@devstudio.com">info@devstudio.com</a>
Додай ще mailto:

2024-02-06 07:02 UTC, xrustics commented on script.js
> +let str = 'lorem ipsum dolor first second third';
Цей код десь використовується? Якщо ні то видали зайве

2024-02-06 09:55 UTC, Danik2021 commented on index.html
> +          <a class="email" href="info@devstudio.com">info@devstudio.com</a>
✔✔✔

2024-02-06 10:08 UTC, Danik2021 commented on index.html
> +        <section class="section-one">
✔✔✔

2024-02-06 10:10 UTC, Danik2021 commented on index.html
> +              <figure class="figure-two">
✔✔✔

2024-02-06 10:12 UTC, Danik2021 commented on index.html
> +                <p class="specialty-two">Frontend Developer</p>
✔✔✔

2024-02-06 10:13 UTC, Danik2021 commented on index.html
> +            <a class="email-two" href="info@devstudio.com">info@devstudio.com</a>
✔✔✔

2024-02-06 10:13 UTC, Danik2021 commented on script.js
> +let str = 'lorem ipsum dolor first second third';
✔✔✔

2024-02-06 10:23 UTC, Danik2021 commented on index.html
> +            <dl>
✔✔✔

2024-02-06 10:41 UTC, Danik2021 commented on index.html
> +            <div class="cont-img-work">
✔✔✔

2024-02-06 10:41 UTC, Danik2021 commented on index.html
> +          <div class="cont-section-four">
✔✔✔

2024-02-06 11:10 UTC, xrustic2020 commented on index.html
> +          <div class="cont-aboutUs-section">
дивись я трохи про інше казав)
ось так треба оформити цей список:
![image](https://github.com/Danik2021/goit-markup-hw-01/assets/59570719/f9fad707-99fd-4592-b93d-715a7c0ba307)

2024-02-06 11:10 UTC, xrustic2020 commented on index.html
> +          <div class="cont-aboutUs-section">
тоді і div не требе)

2024-02-06 11:10 UTC, xrustic2020 commented on index.html
> +            <ul class="ul-img-work">
Ооо! А ось тут супер, зробив правильно 👍

2024-02-06 11:10 UTC, xrustic2020 commented on index.html
> +              <ul class="cont-employee">
а тут неправильно) У тебе має бути один список `ul` а карточки це елементи списку будуть (li а не ul списки), типу так:
`<li class="cont-employee">
                <img src="image/frontend_developer.svg" alt="Olaga Repina" />
                <h3 class="employee">Ольга Рєпіна</h3>
                <p class="specialty">Frontend Developer</p>
              </li>`

2024-02-06 11:10 UTC, xrustic2020 commented on index.html
> +    <div class="wrapper">
подумай, щоб позбутися цього враперу з div, ти ж по факту можеш повісити цей же клас на сам тег body

2024-02-06 11:10 UTC, xrustic2020 commented on index.html
> +            <div class="logo-two">Web<span class="span-logo">Studio</span></div>
"logo-two" - зміни назву на більш точну, типу footer-logo чи якось так. Просто щоб ти розумів по назві що це)

2024-02-06 15:28 UTC, Danik2021 commented on index.html
> +          <div class="cont-aboutUs-section">
✔✔✔

2024-02-06 15:56 UTC, Danik2021 commented on index.html
> +              <ul class="cont-employee">
✔✔✔

2024-02-06 15:59 UTC, Danik2021 commented on index.html
> +    <div class="wrapper">
✔✔✔

2024-02-06 16:00 UTC, Danik2021 commented on index.html
> +            <div class="logo-two">Web<span class="span-logo">Studio</span></div>
✔✔✔

2024-02-07 07:59 UTC, xrustic2020 commented on index.html
> +        <h1>Ефективні рішення для вашого бізнесу</h1>
зауваж, що h1 на сторінці має бути лише один!
Хорошою практикою є використання h1 для логотипу сайту в хедері а далі кожен наступний заголовок дивишся по структурі, типу в хедері лого це h1, в банері "Ефективні рішення для вашого бізнесу" тут краще h2, блок  aboutUs - h3 (як ти вже зробив) і так далі

2024-02-07 07:59 UTC, xrustic2020 commented on index.html
> +        <div class="button">
тут семантично правильніше використати за допомогою тегу button

2024-02-07 07:59 UTC, xrustic2020 commented on index.html
> +      <div class="footer">
давай попробуємо позбутися зайвих div обгорток в футері. Тут же щось можна повісити безпосередньо на тег footer (клас)

2024-02-07 07:59 UTC, xrustic2020 commented on index.html
> +      <div class="logo">
Давай робити одразу як на реальному проекті, лого в хедері як правило це h1 (який має бути один на сторінці), можна зробити так - `<h1><a href="./index.html">...</a></h1>`

2024-02-07 10:47 UTC, Danik2021 commented on index.html
> +        <h1>Ефективні рішення для вашого бізнесу</h1>
✔✔✔

2024-02-07 10:50 UTC, Danik2021 commented on index.html
> +        <div class="button">
✔✔✔

2024-02-07 10:50 UTC, Danik2021 commented on index.html
> +      <div class="footer">
✔✔✔

2024-02-07 10:51 UTC, Danik2021 commented on index.html
> +      <div class="logo">
✔✔✔

2024-02-08 20:05 UTC, xrustic2020 approved these changes
Молодець, все ок 👍

2024-02-09 18:39 UTC, merged