css homework#2
Danik2021/goit-markup-hw-01 pull request #3
Opened 2024-02-14 17:44 UTC by Danik2021

I did css (homework#2)

2024-02-17 12:57 UTC, Denys320 commented on image/normalize.css
> +/*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */
молодец!

2024-02-17 16:10 UTC, Denys320 requested changes

2024-02-17 16:10 UTC, Denys320 commented on index.html
>    </body>
script должен быть внутри body

2024-02-17 16:10 UTC, Denys320 commented on index.html
>      <link rel="stylesheet" href="style.css" />
А2. в проекте должна быть папка с файлами стилей

2024-02-17 16:10 UTC, Denys320 commented on index.html
> +          <ul class="ul-img-work list">
я думаю название класса очень сложное, можно придумать что то попроще и чтобы было понятнее кому то другому, например 'work-name', у списка ul 'work-list'

2024-02-17 16:10 UTC, Denys320 commented on style.css
> +  color: var(--main_text_color);
в боди можно добавить леттер спейс стандартный, а там дальше где нужен будет другой то просто его указать, вместо того чтобы он был везде указан и визуально нагружал код.
точно так же с фонт вейт и другими параметрами в будущем

2024-02-17 16:10 UTC, Denys320 commented on style.css
> +  color: #757575;
тут цвет текста является одним из основных, его так же можно добавить в body и везде указывать через var

2024-02-17 16:10 UTC, Denys320 commented on style.css
> +  color: #2196f3;
так же нужно добавить через var, чтобы не путать никого и самому не запутаться в будущем

2024-02-17 22:17 UTC, xrustic2020 requested changes

2024-02-17 22:17 UTC, xrustic2020 commented on index.html
>    </body>
![Screenshot_2024-02-18-00-05-01-995_com android chrome](https://github.com/Danik2021/goit-markup-hw-01/assets/59570719/659dff4d-5baa-4ec8-b8ee-22f3e8605270)

2024-02-17 22:17 UTC, xrustic2020 commented on index.html
>    </body>
Поддерживаю, немного позже в программе будет эта тема чуть больше раскрыта, пока этой информации (скрин выше) будет достаточно для базового понимания почему так)

2024-02-17 22:17 UTC, xrustic2020 commented on style.css
> +.ourTeam-title {
Я бы тут переделал. Зачем тебе так много классов, чтоб указать на одни и те же стили? Просто сделай один класс, например "section-title" и его можно свободно переиспользовать всюду)

2024-02-17 22:17 UTC, xrustic2020 commented on style.css
> +.cont-aboutUs-section p {
В CSS лучше придерживаться какого-то одного вида форматирования имени классов, например "cont-about-us-section". CamelCase тут ни к чему не нужен)

2024-02-17 22:17 UTC, xrustic2020 commented on index.html
> +          <ul class="ul-img-work list">
@Danik2021 пересмотри пожалуйста комментарий в CSS файле по этим классам. Мне кажется тут можно сделать намного проще с одним классом)

2024-02-19 14:15 UTC, Danik2021 commented on index.html
>    </body>
✔✔✔

2024-02-19 17:03 UTC, Danik2021 commented on index.html
>      <link rel="stylesheet" href="style.css" />
✔✔✔

2024-02-19 17:23 UTC, Danik2021 commented on style.css
> +  color: #757575;
✔✔✔

2024-02-19 17:24 UTC, Danik2021 commented on style.css
> +  color: #2196f3;
✔✔✔

2024-02-19 17:24 UTC, Danik2021 commented on style.css
> +.ourTeam-title {
✔✔✔

2024-02-19 17:46 UTC, Danik2021 commented on style.css
> +.cont-aboutUs-section p {
✔✔✔

2024-02-19 17:56 UTC, Danik2021 commented on index.html
> +          <ul class="ul-img-work list">
✔✔✔

2024-02-21 07:28 UTC, xrustic2020 commented on index.html
> +      <section class="section-title">
не ок для секції ( тег <section) давати класс section-title. Бо по назві - це "заголовок секції" а по факту це блок секції. Якщо ти хочеш дати певний класс для тегу <section> то це може бути більш загальна назва що символізує саме блок, наприклад щось типу:
section, section-block, section-container, section-box, page-section, section-wrapper
Якщо це буде вже якась унікальна секція зі стилями що відрізняються від інших секцій то можна називати по вмісту секції, наприклад:
features-section (секція переваг)

2024-02-21 07:28 UTC, xrustic2020 commented on css/style.css
> +.main-title,
Ці класи десь використовуються? Якщо ні видали їх. Бо це виходить зайвий код що буде сповільнити завантаження сторінки сайту. Якщо цей файл вже не використовується - все аналогічно, просто видаляй його

2024-02-21 17:29 UTC, Danik2021 commented on index.html
> +      <section class="section-title">
✔✔✔

2024-02-21 17:34 UTC, Danik2021 commented on css/style.css
> +.main-title,
✔✔✔

2024-02-22 20:57 UTC, xrustic2020 commented on index.html
> +        <h2 class="our-team-title">Наша команда</h2>
Щось я не знайду в css файлах такого класу... Він використовується? Якщо так - підкажи де він оголошений? Якщо не використовується - просто видали звідси.

2024-02-22 20:57 UTC, xrustics commented on index.html
> +        <h2 class="what-do-title">Чим ми займаємося</h2>
what-do-title - щось цього класу не знаходжу в css файлах. Видали якщо він не використовується

2024-02-22 21:01 UTC, xrustics commented
@Danik2021 переглянь будь ласка всюди класи ( і в css і в  html файлах) познаходь те що не використовується і повидаляй) В проекті не має бути невикористовуємого коду

2024-02-23 12:18 UTC, Danik2021 commented on index.html
> +        <h2 class="our-team-title">Наша команда</h2>
✔✔✔

2024-02-23 12:18 UTC, Danik2021 commented on index.html
> +        <h2 class="what-do-title">Чим ми займаємося</h2>
✔✔✔

2024-02-27 15:29 UTC, Denys320 requested changes

2024-02-27 15:29 UTC, Denys320 commented on index.html
>          <ul class="ul-img-work list">
Я думаю что название класса стало еще сложнее, зачем в теге ul писать в классе то же самое ul, если в теге li есть изображение или еще что то, то это не значит что нужно написать такой сложный класс, "ul-img-work list" можно вообще заменить на "work-list"

2024-02-27 15:29 UTC, Denys320 commented on index.html
>        <section class="section-block">
Класс секции можно так же поменять на слово которое наиболее полно характеризует контент, например "work"

2024-02-28 21:54 UTC, xrustic2020 approved these changes

2024-02-29 18:52 UTC, merged