homework#3
Danik2021/goit-markup-hw-01 pull request #4
Opened 2024-02-29 20:34 UTC by Danik2021

do header and main section

2024-03-02 08:24 UTC, xrustic2020 requested changes

2024-03-02 08:24 UTC, xrustic2020 commented on css/style.css
> +  outline: 3px solid #b1b1bb1b;
Розумію, можливо тобі треба було це для розробки (outline), сам так роблю іноді) але код в ПР - це код готового, виконаного завдання, та в ньому немає бути зайвих елементів. Якщо це не використовується - прибери) Якщо це так треба - то напиши будь ласка для чого саме?)

2024-03-02 08:24 UTC, xrustic2020 commented on css/style.css
> +  padding-bottom: 60px;
Якщо задаєш падінги для чотирьох сторін - то краще через властивість padding: 60px 215px. Це набагато менше місця в коді та більш зручно читається

2024-03-02 08:24 UTC, xrustic2020 commented on css/style.css
> +.nav_menu .nav_li + .nav_li {
Поясни будь ласка чому саме так використав селектор?)
Питаю бо просто це не звична конструкція ".nav_li + .nav_li"

2024-03-02 08:24 UTC, xrustic2020 commented on css/style.css
> +.footer-logo {
Дивись, виходить у нас є 2 класи, що по факту означають те саме - логотип. Розкажи чому саме потрібно 2 класи?) Я просто хочу зрозуміти твою логіку та можливо підкажу як можна зробити краще

2024-03-02 08:24 UTC, xrustic2020 commented on css/style.css
>    font-size: 16px;
Не тільки кольори можна в константи) я б цей розмір шрифту теж виніс би в змінну, бо бачу він використовується декілька разів в документі. Коли думаєш чи треба його в змінну - дивись чи використовується це значення ще десь, і якщо так, то в змінну його)

2024-03-02 08:24 UTC, xrustic2020 commented on css/style.css
>    font-size: 16px;
Зазвичай в змінних тримають основні значення кольорів, розміри шрифтів, розміри основних відступів, тощо. Під словом "основні" я маю на увазі коли ці значення використовується по декілька разів в коді css

2024-03-02 08:24 UTC, xrustic2020 commented on index.html
> +        <h2 class="paragraph">Чим ми займаємося</h2>
Смислово ця назва класу трохи протиречить використанню) Виходить ми використовуємо тег що відповідає за "заголовки" абйому надаємо основний клас з назвою "параграфу". Це можна легко сплутати з тегом <p>  по сенсу. Краще заміни назву на більш підходящою, наприклад "heading" ( перекладається як заголовок), "або з якоюсь приставкою, типу "team- heading" тощо

2024-03-04 16:43 UTC, Danik2021 commented on css/style.css
> +  outline: 3px solid #b1b1bb1b;
Це було для комфорту, Видаляю

2024-03-04 16:43 UTC, Danik2021 commented on css/style.css
> +  padding-bottom: 60px;
✔✔✔

2024-03-04 16:46 UTC, Danik2021 commented on css/style.css
> +.nav_menu .nav_li + .nav_li {
Я так зробив перше, тому що в мене тоді буде у всіх марджин зліва окрім першого елементу. А друге, я такий крутий як Репета))

2024-03-04 16:50 UTC, Danik2021 commented on css/style.css
> +.footer-logo {
Це було помилка, не логіка) я вже виправив

2024-03-04 16:51 UTC, Danik2021 commented on css/style.css
>    font-size: 16px;
✔✔✔

2024-03-04 16:52 UTC, Danik2021 commented on index.html
> +        <h2 class="paragraph">Чим ми займаємося</h2>
✔✔✔

2024-03-05 10:47 UTC, xrustic2020 commented
«A1» У корені проекту є папка **images** з зображеннями.
Переіменуй папку з image на images та всі імпорти зображеннь в проекті відповідно

2024-03-05 10:59 UTC, xrustic2020 commented
<img width="1175" alt="Знімок екрана 2024-03-05 о 12 57 56" src="https://github.com/Danik2021/goit-markup-hw-01/assets/59570719/ecebb1c2-4832-4ce8-bf17-17fddd607faa">

2024-03-05 11:02 UTC, xrustic2020 commented
<img width="1440" alt="Знімок екрана 2024-03-05 о 13 00 57" src="https://github.com/Danik2021/goit-markup-hw-01/assets/59570719/08928414-2a13-4cbd-8bc8-f791eac018c0">

2024-03-09 09:57 UTC, xrustic2020 commented
Зображень немає...
Я знаю в чому річ, але не скажу тобі)
Подумай чого так, потім напиши мені чому так в коментарі, та виправ цю штуку)

![image](https://github.com/Danik2021/goit-markup-hw-01/assets/59570719/d270ddaa-2d4e-40d5-8fd8-2e32b46f8461)

2024-03-09 09:58 UTC, xrustic2020 commented
Завжди перевіряй свою роботу перед сдачею на перевірку)

2024-03-09 09:59 UTC, xrustic2020 commented
Перевір виконання цього завдання:
«B17» У картках на сторінці Портфоліо є рамка (властивість border), але тільки у нижній частині картки.

2024-03-09 09:59 UTC, xrustic2020 requested changes

2024-03-09 09:59 UTC, xrustic2020 commented on css/style.css
>    --accent-color: #2196f3;
«A3» стилі написані в файлі` styles.css`, який знаходиться в папці css
переіменуй style -> styles

2024-03-09 09:59 UTC, xrustic2020 commented on images/frontend_developer.svg
назва файлу потрібно щоб теж відповідала стилю як і по всьому проєкту. Якщо вирішив писати через дефіс - то краще всюди вже через дефіс і писати. Або "-" або "_"

2024-03-09 09:59 UTC, xrustic2020 commented on images/product_designer.svg
назва файлу потрібно щоб теж відповідала стилю як і по всьому проєкту. Якщо вирішив писати через дефіс - то краще всюди вже через дефіс і писати. Або "-" або "_"

2024-03-09 09:59 UTC, xrustic2020 commented on images/ui_designer.svg
назва файлу потрібно щоб теж відповідала стилю як і по всьому проєкту. Якщо вирішив писати через дефіс - то краще всюди вже через дефіс і писати. Або "-" або "_"

2024-03-09 09:59 UTC, xrustic2020 commented on index.html
Переглянь всі теги <link...
там багато дублікатів

2024-03-09 09:59 UTC, xrustic2020 commented on css/style.css
> +  width: 1600px;
на цьому все центрування пішло "по сраці" 😄
Виходить ти обмежив боди до 1600px і вже в цих 1600 центруєш контент. А що якщо у користувача більший екран ніж 1600 ? Тоді виходить у користувача буде боди прижатий о лівого краю та мати ширину 1600, а в цих 1600 вже буде центрування. Подумай сам як це можна виправити. Ось скрін:
<img width="1393" alt="Знімок екрана 2024-03-09 о 11 16 58" src="https://github.com/Danik2021/goit-markup-hw-01/assets/59570719/fb43c39f-a373-4fa3-b7d6-d5f0e1069e9e">

2024-03-09 09:59 UTC, xrustic2020 commented on css/style.css
> +  height: 2346px;
так не можна робити! прибери height
Ти не можеш обмежувати весь боди по висоті, це анті патерн, краще ніколи так не роби

2024-03-09 09:59 UTC, xrustic2020 commented on css/style.css
> +  height: 2346px;
«B12» В елементів відсутня фіксована висота, вона визначається їх контентом.

2024-03-09 09:59 UTC, xrustic2020 commented on index.html
>        <section class="main-section">
Не бачу виконання цього пункту:
«B15» Для всіх секцій використовується один клас .section, задані верхні і нижні падінги по 94px, що відсувають контент всередину секції.
якщо треба додати якісь інші стилі секції - це можна зробити додатковим класом

2024-03-09 15:09 UTC, Danik2021 commented on css/style.css
> +  width: 1600px;
✔✔✔

2024-03-09 15:11 UTC, Danik2021 commented on images/product_designer.svg
✔✔✔

2024-03-09 15:11 UTC, Danik2021 commented on css/style.css
>    --accent-color: #2196f3;
✔✔✔

2024-03-10 11:07 UTC, xrustic2020 commented on css/styles.css
> +  color: #ffffff;
В тебе ж наче вже є змінна для цього коліру, використай її

2024-03-12 18:18 UTC, Danik2021 commented on css/styles.css
> +  color: #ffffff;
✔✔✔

2024-03-12 18:21 UTC, Danik2021 commented on css/style.css
> +  height: 2346px;
✔✔✔

2024-03-12 18:21 UTC, Danik2021 commented on index.html
✔✔✔

2024-03-12 18:21 UTC, Danik2021 commented on images/ui_designer.svg
✔✔✔

2024-03-12 18:21 UTC, Danik2021 commented on images/frontend_developer.svg
✔✔✔

2024-03-12 18:27 UTC, Danik2021 commented on index.html
>        <section class="main-section">
Щось не можу зрозуміти що це потрібно зробити

2024-03-12 19:19 UTC, xrustic2020 commented on index.html
>        <section class="main-section">
Тут схоже як з класом контейнер тільки робиш класс . section  в ньому стилі padding верхній і нижній по 94 px , потім просто додаєш класс на секцію в html. Ну і якщо ці падіннги десь в іншому селекторі задавав, то там треба підчистити

2024-03-13 21:13 UTC, xrustic2020 approved these changes

2024-03-13 21:13 UTC, xrustics commented on index.html
> +      <section class="section-block section">
Бачу що в тебе всі секції з цими двома класами. Можливо варто об'єднати тоді 2 класи в один section?

2024-03-13 21:13 UTC, xrustics commented on portfolio.html
> +      <div class="container">
Це не просто div, тут має бути семантично правильний тег. Подумай який та заміни

2024-03-13 21:13 UTC, xrustic2020 commented on portfolio.html
> +          <li class="list"><button type="button" class="radio button">Усі</button></li>
Це трохи неправильно давати класс list для тегів li. Чому так?
Тег ul розшифровується як "unordered list"  тобто "не нумерований список". Тут ключове слова "list" що означає"список ". А тег li розшифровується як "list item" що в перекладі "елемент чи одиниця списку". Виходить коли ти задаєш тегу li класс list то таке враження на перший погляд що там має бути в кожному li ще по списку)

2024-03-13 21:13 UTC, xrustic2020 commented on portfolio.html
> +          <li class="list"><button type="button" class="radio button">Усі</button></li>
Якщо треба назвати класс для елементу списку називай так щоб було зрозуміло що воно таке) Ось найкращі імена класу для li --->
item, list-item

2024-03-13 21:13 UTC, xrustic2020 commented on index.html
> +          <a class="phone link" href="tel:+380961111111">+38 096 111 11 11</a>
А чому б тобі одразу в css не зробити замість класу link одразу просто на теги "a" кинути стиль text-decoration: none;
Це облегчить тобі потім життя

2024-03-14 17:02 UTC, Danik2021 commented on index.html
> +          <a class="phone link" href="tel:+380961111111">+38 096 111 11 11</a>
✔✔✔

2024-03-14 17:10 UTC, Danik2021 commented on portfolio.html
> +          <li class="list"><button type="button" class="radio button">Усі</button></li>
✔✔✔

2024-03-14 17:11 UTC, Danik2021 commented on portfolio.html
> +      <div class="container">
✔✔✔

2024-03-14 17:16 UTC, Danik2021 commented on index.html
> +      <section class="section-block section">
✔✔✔

2024-03-14 17:17 UTC, merged