The web studio is ready
Danik2021/goit-markup-hw-01 pull request #6
Opened 2024-05-27 12:54 UTC by Danik2021

2024-06-12 13:53 UTC, xrustic2020 requested changes

2024-06-12 13:53 UTC, xrustic2020 commented on close.jpg
Це не jpg, це svg
![image](https://github.com/Danik2021/goit-markup-hw-01/assets/59570719/f93aae51-6db6-4d90-8ca7-673bd682397c)

2024-06-12 13:53 UTC, xrustic2020 commented on css/main.css
> +.add-icons>li>.back-social>svg g {
чому ти так багато вставляєш селекторів з ">" ?
Поясни чим це буде відрізнятись від цього селектору ".add-icons li .back-social svg g" ?

2024-06-12 13:53 UTC, xrustic2020 commented on css/main.css
> +  background-color: rgb(33, 150, 243, 0.9);
колір в константу

2024-06-12 13:53 UTC, xrustic2020 commented on css/main.css
> +  color: #fff;
в константу

2024-06-12 13:53 UTC, xrustic2020 commented on css/styles.css
> +  background-color: rgba(47, 48, 58, 0.8);
колір в константу

2024-06-12 13:53 UTC, xrustic2020 commented on images/icon/close.svg
О, то в тебе все ж є svg, подивись чи потрібно тобі буде тримати додатковий файл цієї ж іконки з jpg

2024-06-18 15:00 UTC, Danik2021 commented on css/main.css
> +.add-icons>li>.back-social>svg g {
✔✔✔

2024-06-18 15:02 UTC, Danik2021 commented on css/main.css
> +  background-color: rgb(33, 150, 243, 0.9);
✔✔✔

2024-06-18 15:04 UTC, Danik2021 commented on images/icon/close.svg
😆

2024-06-18 15:04 UTC, Danik2021 commented on css/styles.css
> +  background-color: rgba(47, 48, 58, 0.8);
✔✔✔

2024-06-18 15:04 UTC, Danik2021 commented on css/main.css
> +  color: #fff;
✔✔✔

2024-06-18 15:04 UTC, Danik2021 commented on images/icon/close.svg
✔✔✔

2024-06-18 15:04 UTC, Danik2021 commented on close.jpg
✔✔✔

2024-06-18 15:04 UTC, Danik2021 commented on close.jpg
Так воно ж мене в svg

2024-06-18 15:32 UTC, merged