homework#6
Danik2021/goit-markup-hw-01 pull request #7
Opened 2024-06-18 15:49 UTC by Danik2021

2024-06-21 06:19 UTC, xrustic2020 requested changes

2024-06-21 06:19 UTC, xrustic2020 commented on index.html
> +            <a class="subscribe-link" href="#">
це не посилання) це кнопка

Сприймай посилання, як елемент, коли треба кудись перенаправити користувача, наприклад на іншу сторінку сайту. Це більше актуально для текстового контенту, по натисканню на який треба кудись направити користувача, на якусь іншу сторінку. Прикріплю пару скріншотів для прикладу

Тим не менш й тут є виключення, якщо елемент виглядає як кнопка, навіть якщо він просто кудись веде користувача (на іншу сторінку наприклад) то це теж "кнопка"

![image](https://github.com/Danik2021/goit-markup-hw-01/assets/59570719/47adb8d9-5836-4a2f-b3ff-3ac24616ed8d)
![image](https://github.com/Danik2021/goit-markup-hw-01/assets/59570719/1e5a1cf0-fc5c-4512-b12e-11475e4632e7)

2024-06-21 06:19 UTC, xrustic2020 commented on portfolio.html
> +            <a class="subscribe-link" href="#">
це не посилання) тут треба не тег <a> а щось інше)

2024-06-21 06:19 UTC, xrustic2020 commented on portfolio.html
> +            <a class="subscribe-link" href="#">
а ще глянь до цього пункту:
«B9» Кнопкам «відправлення» форм заданий атрибут type="submit".

2024-06-21 06:19 UTC, xrustic2020 commented on portfolio.html
> +            <a class="subscribe-link" href="#">
кнопка "Підписатися" - в даному випадку вважається кнопкою відправлення форми. Ти по факту щось ввів в інпут, свій емейл і далі тобі треба його віправити на бекенд, щоб користувачю потім на цей емейл присилати листи

2024-06-21 06:20 UTC, xrustics commented
@Danik2021 бачу що тут ще багато чого не виконано по завданню, немає модалки з формою, тощо. Переглянь будь ласка ще раз вимоги до домашки №6

2024-06-25 17:44 UTC, xrustic2020 commented
![image](https://github.com/Danik2021/goit-markup-hw-01/assets/59570719/37e0ee16-ce87-4808-83a0-d1a1cea518a6)

2024-06-25 17:51 UTC, xrustic2020 commented
![image](https://github.com/Danik2021/goit-markup-hw-01/assets/59570719/298cd0e2-1a14-4853-8a96-3838b5d20ab1)

2024-06-25 17:53 UTC, xrustic2020 commented
![image](https://github.com/Danik2021/goit-markup-hw-01/assets/59570719/a9849edd-a6c3-4f1c-a144-d67e791287bc)

2024-06-25 17:55 UTC, xrustic2020 commented
![image](https://github.com/Danik2021/goit-markup-hw-01/assets/59570719/b776127c-f25f-458c-a9a9-cfb16e1862e7)

2024-06-25 17:57 UTC, xrustic2020 commented
«C6» Для всіх ефектів ховера і фокуса (колір, фон, тінь) зроблені переходи. час - 250ms, функція розподілу часу - cubic-bezier(0.4, 0, 0.2, 1).

Виконання цього пункту не помітив, це треба для всіх ховерів)

2024-06-25 17:57 UTC, xrustic2020 requested changes

2024-06-25 17:57 UTC, xrustic2020 commented on index.html
> +            <a class="subscribe-link" href="#">
@Danik2021 тут нічого не змінилося)

2024-06-25 17:57 UTC, xrustic2020 commented on portfolio.html
> +            <a class="subscribe-link" href="#">
@Danik2021 глянь коментарі тут)

2024-06-26 13:11 UTC, Danik2021 commented on index.html
> +            <a class="subscribe-link" href="#">
✔✔✔

2024-06-26 13:29 UTC, Danik2021 commented on portfolio.html
> +            <a class="subscribe-link" href="#">
✔✔✔

2024-06-29 14:36 UTC, xrustic2020 commented
![image](https://github.com/Danik2021/goit-markup-hw-01/assets/59570719/1bee042c-45fc-4621-9dcf-84b33ad6cb44)

2024-07-03 13:20 UTC, merged