homework#7 refactoring
Danik2021/goit-markup-hw-01 pull request #9
Opened 2024-07-24 09:19 UTC by Danik2021

- add sass instead css

2024-08-08 20:54 UTC, xrustic2020 requested changes

2024-08-08 20:54 UTC, xrustic2020 commented on index.html
> +      <div class="container-add">
Префікс "add" перекладається як "додати", що не зовсім відповідає тому що тут за контент. Краще назвати з префіксом "join" замість "add". Ну і нижче теж назви класів треба змінити, заміни "add" на "join"

2024-08-08 20:54 UTC, xrustic2020 commented on index.html
> +          <li class="add__back">
Ця назва класу взагалі щось незрозуміле, спробуй запхати в перекладач Гугл фразу "add back" і подивись що перекладе на українську))

2024-08-08 20:54 UTC, xrustic2020 commented on index.html
> +        <div class="subscribe__cont">
На майбутнє не використовуй скорочення в назві класів типу як "cont", бо ти зрозумієш А після тебе розробник може не зрозуміти. Краще без скорочень

2024-08-08 20:54 UTC, xrustic2020 commented on index.html
> +          <button type="submit" class="subscribe__link">
По контенту тут краще клас назвати не -link, краще  -button. Link - це більше для посилань підійде де тег <а

2024-08-08 20:54 UTC, xrustic2020 commented on sass/components/_clients.scss
> +    border: 2px solid #2196f3;
Мені здається це неправильним рішенням. Чому? Бо плавності не буде. Виходить що при ховері весь контент посунеться донизу, бо сюди впихнеться бордер 2px. Подумай та напиши мені які ще можливі рішення ти бачиш

2024-08-08 20:54 UTC, xrustic2020 commented on sass/main.scss
> +  './components2/main', './components2/projects', './components2/footer', './components2/form';
Чому такі назви "components 2" "utils2" , чому їх 2-є?

2024-08-08 20:54 UTC, xrustic2020 commented on sass/components/_employee.scss
> +    font-size: 16px;
Чого не використовуєш свої variables ? Там же є цей шрифт в константі

2024-08-08 20:54 UTC, xrustic2020 commented on sass/components/_employee.scss
> +  background-color: #ffffff;
Чому не з константи з variables?

2024-08-08 20:54 UTC, xrustic2020 commented
Потрібно зідзвонитися по цьому ПРу, бо у мене є питання

2024-08-09 08:30 UTC, Danik2021 commented on sass/main.scss
> +  './components2/main', './components2/projects', './components2/footer', './components2/form';
Вони в мене для portofolio.html 
Мені назви також не подобаються але не можу найти другий варіант

2024-08-09 15:21 UTC, Danik2021 commented on index.html
> +      <div class="container-add">
✔✔✔

2024-08-09 15:24 UTC, Danik2021 commented on index.html
> +          <li class="add__back">
✔✔✔

2024-08-09 15:24 UTC, Danik2021 commented on index.html
> +          <li class="add__back">
Це було задумана типо як background )

2024-08-09 15:28 UTC, Danik2021 commented on index.html
> +        <div class="subscribe__cont">
окей

2024-08-09 15:28 UTC, Danik2021 commented on index.html
> +          <button type="submit" class="subscribe__link">
✔✔✔

2024-08-09 15:36 UTC, Danik2021 commented on sass/components/_clients.scss
> +    border: 2px solid #2196f3;
![Зображення 09 08 24 о 17 35](https://github.com/user-attachments/assets/4022ad54-db34-4e36-a3b8-92bd98a03295)
Дивись, там же цей бордер і так є, він просто переходить в другий колір

2024-08-09 15:44 UTC, Danik2021 commented on sass/components/_employee.scss
> +  background-color: #ffffff;
✔✔✔

2024-08-09 15:44 UTC, Danik2021 commented on sass/components/_employee.scss
> +    font-size: 16px;
✔✔✔

2024-08-09 15:44 UTC, Danik2021 commented on sass/components/_employee.scss
> +  background-color: #ffffff;
✔✔✔

2024-08-09 18:48 UTC, xrustic2020 commented
![image](https://github.com/user-attachments/assets/cce4f2e5-416e-47ce-9752-065aa866698a)

2024-08-09 18:58 UTC, xrustic2020 commented
![image](https://github.com/user-attachments/assets/bfa1a742-ce73-4bb6-a61f-4db3f438c897)

2024-08-09 19:06 UTC, xrustic2020 commented
![image](https://github.com/user-attachments/assets/a3942ab5-8658-44ed-a7d6-90a0ed1b3e02)

2024-08-09 19:08 UTC, xrustic2020 commented
![image](https://github.com/user-attachments/assets/8dcc9f5e-4c5c-41a8-aff5-a56aaaee74f5)

2024-08-09 19:11 UTC, xrustic2020 commented
![image](https://github.com/user-attachments/assets/b2e8f88e-f9db-468e-ba79-fb2a02cc018a)

2024-08-09 19:20 UTC, xrustic2020 commented
![image](https://github.com/user-attachments/assets/573f4027-1e26-4c9a-84d8-80e6ed3ebaf4)

2024-08-09 19:24 UTC, xrustic2020 commented
![image](https://github.com/user-attachments/assets/c8c94129-44ae-44e8-8009-18f44681bd45)

2024-08-09 19:25 UTC, xrustic2020 commented
![image](https://github.com/user-attachments/assets/8a99b9a5-6601-451d-b2c4-a2ef23d92403)

2024-08-09 19:27 UTC, xrustic2020 commented
![image](https://github.com/user-attachments/assets/34a5b201-de2f-4854-b448-2bd029929dba)

2024-08-09 19:29 UTC, xrustic2020 commented
![image](https://github.com/user-attachments/assets/b87541b2-d49a-465e-b481-467daa5b2c6d)

2024-08-09 19:31 UTC, xrustic2020 commented
![image](https://github.com/user-attachments/assets/2996a601-2783-457d-867c-942d7c01b735)

2024-08-09 19:32 UTC, xrustic2020 requested changes

2024-08-09 19:32 UTC, xrustics commented on index.html
> +            <ul class="cont-icons">
cont-icons

2024-08-09 19:32 UTC, xrustics commented on index.html
> +            <ul class="cont-icons">
icon-container | icon-wrap

2024-08-09 19:32 UTC, xrustics commented on index.html
> +            <ul class="cont-icons">
socials

2024-08-09 19:32 UTC, xrustics commented on index.html
> +                <a class="back-social" href="#">
social__link

2024-08-09 19:32 UTC, xrustics commented on index.html
> +    <section class="clients-section section">
clients

2024-08-09 19:32 UTC, xrustics commented on index.html
> +      <div class="container-join">
footer-container

2024-08-09 19:32 UTC, xrustics commented on index.html
> +          <li class="add__background">
footer__social-title
footer__social-list
footer__social-item

2024-08-09 19:32 UTC, xrustics commented on index.html
> +      <h2 class="modal-title">Залиште свої дані, ми вам передзвонимо</h2>
modal__title

2024-08-09 19:32 UTC, xrustics commented on index.html
> +        <label class="form-cont form__cont">
form-label || form-input-label

2024-08-09 19:32 UTC, xrustics commented on index.html
> +          <span class="label-text">Імʼя</span>
form-input__text

2024-08-09 19:32 UTC, xrustics commented on index.html
> +          <span class="form-svg">
form-input__icon

2024-08-09 19:32 UTC, xrustics commented on index.html
> +        <label class="label-textarea" for="textarea">Коментар</label>
comment-field-label

2024-08-09 19:32 UTC, xrustics commented on index.html
> +        <textarea class="textarea" id="textarea" placeholder="Введіть текст"></textarea>
comment-field

2024-08-09 19:32 UTC, xrustics commented on index.html
> +        <label class="form__cont form__cont--checkbox">
checkbox-label

2024-08-09 19:32 UTC, xrustics commented on portfolio.html
> +        <a href="./index.html"> <span class="span-logo header__span">Web</span>Studio</a>
header__logo-link

2024-08-09 19:32 UTC, xrustics commented on portfolio.html
> +          <li class="nav__li"><a href="./portfolio.html">Портфоліо</a></li>
nav__item

2024-08-09 19:32 UTC, xrustics commented on portfolio.html
> +          <div class="projects__cont">
projects-container

2024-08-09 19:32 UTC, xrustics commented on portfolio.html
>            <a href="./index.html"><span class="span-logo">Web</span>Studio</a>
давай зробимо через модифікатор з лого хедеру

2024-08-09 19:32 UTC, xrustics commented on portfolio.html
> +      <div class="container-add">
заміни по аналогії з index.html

2024-08-11 15:52 UTC, Danik2021 commented on index.html
> +            <ul class="cont-icons">
✔✔✔

2024-08-11 15:55 UTC, Danik2021 commented on index.html
> +                <a class="back-social" href="#">
✔✔✔

2024-08-11 15:55 UTC, Danik2021 commented on index.html
> +    <section class="clients-section section">
✔✔✔

2024-08-11 16:02 UTC, Danik2021 commented on index.html
> +      <div class="container-join">
✔✔✔

2024-08-11 16:02 UTC, Danik2021 commented on index.html
> +          <li class="add__background">
✔✔✔

2024-08-11 16:03 UTC, Danik2021 commented on index.html
> +      <h2 class="modal-title">Залиште свої дані, ми вам передзвонимо</h2>
✔✔✔

2024-08-11 16:06 UTC, Danik2021 commented on index.html
> +        <label class="form-cont form__cont">
✔✔✔

2024-08-11 16:49 UTC, Danik2021 commented on index.html
> +          <span class="label-text">Імʼя</span>
✔✔✔

2024-08-11 16:52 UTC, Danik2021 commented on index.html
> +          <span class="form-svg">
✔✔✔

2024-08-11 16:52 UTC, Danik2021 commented on index.html
> +        <label class="label-textarea" for="textarea">Коментар</label>
✔✔✔

2024-08-11 16:53 UTC, Danik2021 commented on index.html
> +        <textarea class="textarea" id="textarea" placeholder="Введіть текст"></textarea>
✔✔✔

2024-08-11 16:55 UTC, Danik2021 commented on index.html
> +        <label class="form__cont form__cont--checkbox">
✔✔✔

2024-08-11 16:57 UTC, Danik2021 commented on portfolio.html
> +        <a href="./index.html"> <span class="span-logo header__span">Web</span>Studio</a>
✔✔✔

2024-08-12 07:21 UTC, Danik2021 commented on portfolio.html
> +        <a href="./index.html"> <span class="span-logo header__span">Web</span>Studio</a>
Там просто лишній клас був. Там  на logo базові стилі і більше нічого не треба

2024-08-12 07:27 UTC, Danik2021 commented on portfolio.html
> +          <div class="projects__cont">
✔✔✔

2024-08-12 07:33 UTC, Danik2021 commented on portfolio.html
>            <a href="./index.html"><span class="span-logo">Web</span>Studio</a>
✔✔✔

2024-08-12 07:34 UTC, Danik2021 commented on portfolio.html
> +      <div class="container-add">
✔✔✔

2024-08-12 14:49 UTC, xrustic2020 commented
![image](https://github.com/user-attachments/assets/137e0ee6-58a9-4de6-9976-d3149239d7f7)
Тут щось поламалось, не натискається чекбокс

2024-08-12 14:50 UTC, xrustic2020 commented
> ![image](https://private-user-images.githubusercontent.com/59570719/356732240-2996a601-2783-457d-867c-942d7c01b735.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NzM4NTksIm5iZiI6MTcyMzQ3MzU1OSwicGF0aCI6Ii81OTU3MDcxOS8zNTY3MzIyNDAtMjk5NmE2MDEtMjc4My00NTdkLTg2N2MtOTQyZDdjMDFiNzM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDE0MzkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3MzhhNzQzNTg1OTAzNjVkNGYzNjU3ZTlhMjRlNzI3MTYzZWFmZjZmY2ZhMDUxZjE4MDJiZGQ2MTkwMzkxNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2ur2AhXJqYWz_5Xi6-p09vXrkju7oJUa0VaVX1oSr5o)

це не виконав

2024-08-12 14:51 UTC, xrustic2020 commented
> ![image](https://private-user-images.githubusercontent.com/59570719/356726527-b2e8f88e-f9db-468e-ba79-fb2a02cc018a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NzM4NTksIm5iZiI6MTcyMzQ3MzU1OSwicGF0aCI6Ii81OTU3MDcxOS8zNTY3MjY1MjctYjJlOGY4OGUtZjlkYi00NjhlLWJhNzktZmIyYTAyY2MwMThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDE0MzkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NzEwZDc2MjM5N2I2NDhkNzNhZDM2ZTczYzcxNTkzM2JhMjhkNjQ2NGQyNjlmYmM3NjY0NWU5MzIyYTc2M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5RkbQ3O6kZ0PvV3_d28fBbGWg-bE2ZZ8F0wImnJKJ5U)

тут розмір шрифту не пофіксив

2024-08-12 14:52 UTC, xrustics commented on index.html
> +        <a href="./index.html"> <span class="span-logo header__span">Web</span>Studio</a>
Здається ти казав що тут клас span-logo не використовується і ще ми домовлялися змінити назву класу header__span, перевір будь ласка ці моменти, можливо просто не всюди замінив

2024-08-12 14:52 UTC, xrustic2020 commented on index.html
> +        <div class="form__subscribe-cont subscribe__cont">
тут немає зайвого класу, який більше не використовується?

2024-08-12 14:52 UTC, xrustic2020 commented on index.html
> +        <label class="comment-field-label label-textarea" for="textarea">Коментар</label>
чи немає тут зайвого класу?

2024-08-12 14:52 UTC, xrustic2020 commented on sass/components/_clients.scss
> +    border: 2px solid #2196f3;
ок, згоден, дякую що прояснив 👍

2024-08-12 14:52 UTC, xrustic2020 commented on sass/components/_about.scss
> +  color: #757575;
переглянь будь ласка стилі, та там де в тебе є вже variables - використай ці змінні

2024-08-12 14:52 UTC, xrustic2020 commented on sass/components/_employee.scss
> +  background-color: #ffffff;
щось тут досі не з variables)

2024-08-12 14:52 UTC, xrustic2020 commented on sass/main.scss
> +  './components2/main', './components2/projects', './components2/footer', './components2/form';
це треба буде змінити, може давай з наступним ПРом проговоримо та пофіксимо

2024-08-13 06:01 UTC, Danik2021 commented on sass/components/_employee.scss
> +  background-color: #ffffff;
я все передився по всьому документу тепер з змінних

2024-08-13 06:01 UTC, Danik2021 commented on sass/components/_employee.scss
> +  background-color: #ffffff;
✔✔✔

2024-08-13 06:04 UTC, Danik2021 commented on index.html
> +        <div class="form__subscribe-cont subscribe__cont">
Зайві класи видалив

2024-08-13 06:04 UTC, Danik2021 commented on index.html
> +        <div class="form__subscribe-cont subscribe__cont">
✔✔✔

2024-08-13 06:05 UTC, Danik2021 commented on index.html
> +        <label class="comment-field-label label-textarea" for="textarea">Коментар</label>
Зайвий клас видалив

2024-08-13 06:05 UTC, Danik2021 commented on index.html
> +        <label class="comment-field-label label-textarea" for="textarea">Коментар</label>
✔✔✔

2024-08-13 06:05 UTC, Danik2021 commented on sass/components/_about.scss
> +  color: #757575;
✔✔✔

2024-08-13 06:07 UTC, Danik2021 commented on index.html
> +        <a href="./index.html"> <span class="span-logo header__span">Web</span>Studio</a>
header__span - використовується, а вот span-logo ні

2024-08-13 06:08 UTC, Danik2021 commented on index.html
> +        <a href="./index.html"> <span class="span-logo header__span">Web</span>Studio</a>
видалив span-logo, та з хедеру header__logo тому що він не використовується

2024-08-13 06:08 UTC, Danik2021 commented on index.html
> +        <a href="./index.html"> <span class="span-logo header__span">Web</span>Studio</a>
✔✔✔

2024-08-16 04:44 UTC, xrustic2020 approved these changes

2024-08-16 04:44 UTC, xrustic2020 commented on index.html
> +        <a href="./index.html"> <span class="header__span">Web</span>Studio</a>
Пам'ятаєш ми казали що це буде класс не span?)
Нижче запропоную тобі пару рішень, обери яке тобі краще:
1. logo--blue
2. logo__accent
3. logo__left-side

2024-08-16 04:44 UTC, xrustic2020 commented on portfolio.html
> +        <a href="./index.html"> <span class="header__span">Web</span>Studio</a>
Тут по аналогії з index.html замінити

2024-08-16 04:44 UTC, xrustic2020 commented on portfolio.html
>            <a href="./index.html"><span class="span-logo">Web</span>Studio</a>
Щось тут не змінилося)

2024-08-16 04:44 UTC, xrustic2020 commented on sass/components/_employee.scss
> +  background-color: #f5f4fa;
Вже не в перше зустрічаю цей колір, краще його в константу.
Треба запам'ятати це як правило - якщо колір в css зустрічається більше одного разу то ми його пхаємо в константу

2024-08-16 07:25 UTC, Danik2021 commented on index.html
> +        <a href="./index.html"> <span class="header__span">Web</span>Studio</a>
✔✔✔

2024-08-16 07:25 UTC, Danik2021 commented on portfolio.html
> +        <a href="./index.html"> <span class="header__span">Web</span>Studio</a>
✔✔✔

2024-08-16 07:36 UTC, Danik2021 commented on sass/components/_employee.scss
> +  background-color: #f5f4fa;
✔✔✔

2024-08-16 17:33 UTC, Danik2021 commented on portfolio.html
>            <a href="./index.html"><span class="span-logo">Web</span>Studio</a>
✔✔✔

2024-08-16 17:38 UTC, merged